# Generated by Django 5.1.7 on 2025-03-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_index',
            field=models.IntegerField(default=0),
        ),
    ]
